---

- hosts: localhost
  connection: local
  environment:
    PATH: "/home/tuka/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  vars:
    user: tuka
    user_name: Tsukasa Nishiyama
    user_email: tsukasa@birdcage.jp
    github_user: tukaelu
    timezone: Asia/Tokyo
    ci_skip: "{{ lookup('env', 'CI_SKIP') }}"
  roles:
    - base
    - thinkpad
    - python
    - zsh
    - fzf
    - anyenv
    - software
    - neovim
    - conky
    - yubikey
    - libinput-gestures
    - xremap
    - kubernetes
    - terraform
