---

- name: clone repo
  git:
    repo: https://github.com/k0kubun/xremap.git
    dest: /home/tuka/Repos/misc/xremap
    depth: 1

- name: make
  command: make
  args:
    chdir: /home/tuka/Repos/misc/xremap

- name: make install
  become: yes
  command: make install
  args:
    chdir: /home/tuka/Repos/misc/xremap
