---

- name: install python packages
  become: yes
  apt:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ python_packages }}'

- name: install pip packages
  pip:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ pip_packages }}'
